### ISSUE TITLE
all paxels except diamond and vibranium have incorrect mining levels

### ISSUE THREAD

**Issue by AwwShoot** [Brandcraf06/AdabraniumMod#2]
While the mine quickly, none of the paxels except diamond and vibranium will actually drop stone/ore they mine.

**Comment by Brandcraf06** [comment]
Thanks for report but after testing, the paxels have the same mining level as the corresponding material and drop all blocks he can. Be careful, like some vanilla tools, some blocks can't be obtained with some paxel. For example, the iron ore cannot be obtained with a wooden and gold paxel.
