### ISSUE TITLE
1.20.1 [Crash]

### ISSUE THREAD

**Issue by Gomez96** [Brandcraf06/AdabraniumMod#26]
The newest version of the mod doesn't work: ''The game crashed whilst starting integrated server
Error: java.lang.IllegalArgumentException: Couldn't find registry entry for ResourceKey[minecraft:worldgen/placed_feature / adabranium:ore_adamantine]''

Log and crash-reports: https://mega.nz/file/3dBCHajK#BC94e8Ir0rRVhHx9pfvC9cTKROcFtdD8cxcoqGvfzns

**Comment by Brandcraf06** [comment]
Indeed, thanks for reporting it, the auto publication didn't take into account some .json files.

**Comment by Brandcraf06** [comment]
It's all good!
https://legacy.curseforge.com/minecraft/mc-mods/adabranium/files/4687411
