### ISSUE TITLE
Adamantium Pick issue

### ISSUE THREAD

**Issue by DanShu15** [Brandcraf06/AdabraniumMod#5]
It seems there's a problem with adamantium picks and bulky shulkers. I'm not sure if it's affected regular shulkers, but I don't think so. I'll post in both because it sounds like the shulker itself was fine, it contents just disappeared.

Client Log:
https://pastebin.com/bBK607Tv
Server Log:
https://pastebin.com/zxDdPfPP

**Comment by i509VCB** [comment]
You seem to have `diggusmaximus` installed. I do remember it having an issue at one point where veinmining a block will not preserve nbt data.

I'd assume the pick is just a normal `PickaxeItem`, so I would immediately attribute it as the root cause.

Otherwise, I'd need to look further into this

**Comment by DanShu15** [comment]
Interesting, I'll ask if they were holding the hotkey at the time 🙂 we also have more enchantments from a mod, including a veinmining and tree cutting enchant. I've asked if that's a possibility as well

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DanShu15** [comment]
Turns out the pick did have the veining enchantment on it, so that's likely what the problem was
